### ISSUE TITLE
Error spamming in console

### ISSUE THREAD

**Issue by risingvalhalla** [Draylar/miners-horizon#13]
Hello!
I'm getting an error spamming in the console, can't clarify if its something related to your mod or maybe something from my side but here is the log.

> [22:30:34] [Server thread/ERROR]: Could not save data net.minecraft.class_3767@6c95fc09
java.io.FileNotFoundException: ./world/DIM_miners_horizon/data/raidsminers_horizon_miners_horizon.dat (No such file or directory)
at java.io.FileOutputStream.open0(Native Method) ~[?:1.8.0_212]
at java.io.FileOutputStream.open(FileOutputStream.java:270) ~[?:1.8.0_212]
at java.io.FileOutputStream.<init>(FileOutputStream.java:213) ~[?:1.8.0_212]
at java.io.FileOutputStream.<init>(FileOutputStream.java:162) ~[?:1.8.0_212]
at net.minecraft.class_18.method_17919(class_18.java:51) [intermediary-vanilla_1_14_1.jar:?]
at net.minecraft.class_26.method_125(class_26.java:111) [intermediary-vanilla_1_14_1.jar:?]
at net.minecraft.class_3218.method_14188(class_3218.java:747) [intermediary-vanilla_1_14_1.jar:?]
at net.minecraft.class_3218.method_14176(class_3218.java:736) [intermediary-vanilla_1_14_1.jar:?]
at net.minecraft.server.MinecraftServer.method_3723(MinecraftServer.java:529) [intermediary-vanilla_1_14_1.jar:?]
at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:783) [intermediary-vanilla_1_14_1.jar:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:632) [intermediary-vanilla_1_14_1.jar:?]
at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]

PS: Sorry for the grammatical errors... english is not my native language ^^

**Comment by Draylar** [comment]
Seems like vanilla is trying to do raid related activities in the dimension. Haven't seen this one before, but I'll see what I can do.
